// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/catalog/{id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Catalog"
                ],
                "summary": "Get Catalog",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Catalog ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/v1.V1SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/view.MediaRecordCatalog"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/collection/all": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Collection"
                ],
                "summary": "Get a User's Collections",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/v1.V1SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/view.CollectionObject"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/collection/new": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Collection"
                ],
                "summary": "Create New Collection",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/v1.V1SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/collection/recent": {
            "get": {
                "description": "Gets 20 most recent records added to any collection",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Collection"
                ],
                "summary": "Get User's Recent Collection Records",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/v1.V1SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/view.MediaRecordCatalog"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/collection/{id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Collection"
                ],
                "summary": "Get Collection Contents",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Collection ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/v1.V1SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/view.CollectionView"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Collection"
                ],
                "summary": "Add Media to Collection",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Collection ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Add to Collection Request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.AddToCollectionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/v1.V1SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Collection"
                ],
                "summary": "Delete A Media from Collection",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Collection ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Add to Collection Request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.AddToCollectionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/v1.V1SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/collection/{id}/delete": {
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Collection"
                ],
                "summary": "Delete Collection",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Collection ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/v1.V1SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "database.GenreObject": {
            "type": "object",
            "properties": {
                "genre": {
                    "type": "string"
                },
                "genre_id": {
                    "type": "integer"
                },
                "media_source": {
                    "type": "string"
                },
                "media_type": {
                    "type": "string"
                },
                "source_id": {
                    "type": "integer"
                }
            }
        },
        "database.TagObject": {
            "type": "object",
            "properties": {
                "tagID": {
                    "type": "integer",
                    "format": "int64"
                },
                "tagName": {
                    "type": "string"
                }
            }
        },
        "v1.AddToCollectionRequest": {
            "type": "object",
            "required": [
                "media_source",
                "media_type",
                "source_id"
            ],
            "properties": {
                "collection_id": {
                    "type": "integer"
                },
                "media_source": {
                    "type": "string"
                },
                "media_type": {
                    "type": "string"
                },
                "source_id": {
                    "type": "string"
                }
            }
        },
        "v1.V1ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "error message"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "success",
                        "error"
                    ],
                    "example": "error"
                }
            }
        },
        "v1.V1SuccessResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "status": {
                    "type": "string",
                    "enum": [
                        "success",
                        "error"
                    ],
                    "example": "success"
                }
            }
        },
        "view.CollectionObject": {
            "type": "object",
            "properties": {
                "collection_id": {
                    "type": "integer"
                },
                "collection_title": {
                    "description": "my collection, etc.",
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "is_public": {
                    "type": "boolean"
                },
                "owner_username": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/database.TagObject"
                    }
                },
                "thumbnail_uri": {
                    "description": "url for media thumbnails",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "view.CollectionView": {
            "type": "object",
            "properties": {
                "collection": {
                    "$ref": "#/definitions/view.CollectionObject"
                },
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/view.MediaRecordCatalog"
                    }
                },
                "total_records": {
                    "type": "integer"
                }
            }
        },
        "view.Credit": {
            "type": "object",
            "required": [
                "meta_source",
                "source_id"
            ],
            "properties": {
                "character": {
                    "type": "string"
                },
                "credit_id": {
                    "type": "string"
                },
                "job": {
                    "description": "cast, director, etc.",
                    "type": "string"
                },
                "meta_source": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "original_name": {
                    "type": "string"
                },
                "source_id": {
                    "type": "string"
                },
                "thumbnail_uri": {
                    "description": "profile pic of person",
                    "type": "string"
                }
            }
        },
        "view.MediaRecordCatalog": {
            "type": "object",
            "required": [
                "media_source",
                "media_title",
                "media_type",
                "source_id"
            ],
            "properties": {
                "backdrop_uri": {
                    "type": "string"
                },
                "cast": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/view.Credit"
                    }
                },
                "creators": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/view.Credit"
                    }
                },
                "duration": {
                    "description": "duration/runtime in minutes",
                    "type": "integer"
                },
                "episode_count": {
                    "type": "integer"
                },
                "episode_number": {
                    "type": "integer"
                },
                "extra_data": {
                    "type": "object",
                    "additionalProperties": true
                },
                "genres": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/database.GenreObject"
                    }
                },
                "guest_stars": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/view.Credit"
                    }
                },
                "last_air_date": {
                    "description": "for shows, latest episode air date",
                    "type": "string"
                },
                "logo_uri": {
                    "type": "string"
                },
                "media_source": {
                    "description": "tmdb, openlibrary, etc",
                    "type": "string"
                },
                "media_title": {
                    "type": "string"
                },
                "media_type": {
                    "type": "string"
                },
                "next_air_date": {
                    "description": "for shows, next scheduled episode air date",
                    "type": "string"
                },
                "origin_country": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "original_language": {
                    "type": "string"
                },
                "original_title": {
                    "type": "string"
                },
                "overview": {
                    "type": "string"
                },
                "popularity": {
                    "type": "number"
                },
                "release_date": {
                    "type": "string"
                },
                "season_count": {
                    "type": "integer"
                },
                "season_number": {
                    "type": "integer"
                },
                "source_id": {
                    "type": "string"
                },
                "status": {
                    "description": "Returning Series, Released, etc.",
                    "type": "string"
                },
                "thumbnail_uri": {
                    "type": "string"
                },
                "vote_average": {
                    "type": "number"
                },
                "vote_count": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "beta-0.1.0",
	Host:             "localhost:2323",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Hound API Documentation",
	Description:      "Hound Media Server Documentation",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
