// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/catalog/{id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Catalog"
                ],
                "summary": "Get Catalog",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Catalog ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/v1.V1SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/view.MediaRecordCatalog"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    }
                }
            }
        },
        "/movie/{id}/history/delete": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Watch History"
                ],
                "summary": "Delete Movie Watch History",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Media ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Watch Event IDs to delete",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.DeleteWatchHistoryPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/v1.V1SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tv/{id}/history/delete": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Watch History"
                ],
                "summary": "Delete TV Show Watch History",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Media ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Watch Event IDs to delete",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.DeleteWatchHistoryPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/v1.V1SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/collection/all": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Collection"
                ],
                "summary": "Get a User's Collections",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/v1.V1SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/view.CollectionObject"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/collection/new": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Collection"
                ],
                "summary": "Create New Collection",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/v1.V1SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/collection/recent": {
            "get": {
                "description": "Gets 20 most recent records added to any collection",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Collection"
                ],
                "summary": "Get User's Recent Collection Records",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/v1.V1SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/view.MediaRecordCatalog"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/collection/{id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Collection"
                ],
                "summary": "Get Collection Contents",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Collection ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/v1.V1SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/view.CollectionView"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Collection"
                ],
                "summary": "Add Media to Collection",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Collection ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Add to Collection Request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.AddToCollectionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/v1.V1SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Collection"
                ],
                "summary": "Delete A Media from Collection",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Collection ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Add to Collection Request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.AddToCollectionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/v1.V1SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/collection/{id}/delete": {
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Collection"
                ],
                "summary": "Delete Collection",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Collection ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/v1.V1SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/movie/search": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Movie",
                    "Search"
                ],
                "summary": "Search Movies",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search Query",
                        "name": "query",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/v1.V1SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/view.MediaRecordCatalog"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/movie/{id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Movie"
                ],
                "summary": "Get Movie Details",
                "parameters": [
                    {
                        "type": "string",
                        "example": "tmdb-1234",
                        "description": "Media ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/v1.V1SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/view.MediaRecordCatalog"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/movie/{id}/history": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Watch History"
                ],
                "summary": "Get Movie Watch History",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Media ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/v1.V1SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/view.MediaRewatchRecordWatchEvents"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Watch History"
                ],
                "summary": "Add Movie Watch History",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Media ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Watch History Payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.WatchHistoryMoviePayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/v1.V1SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/movie/{id}/playback": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Watch Progress"
                ],
                "summary": "Get Playback Progress",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Media ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/v1.V1SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Watch Progress"
                ],
                "summary": "Set Playback Progress",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Media ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Watch Progress Payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.WatchProgress"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/v1.V1SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/movie/{id}/playback/delete": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Watch Progress"
                ],
                "summary": "Delete Playback Progress",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Media ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Delete Payload (only for TV)",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/v1.DeletePlaybackProgressPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/v1.V1SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/tv/search": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "TV Show",
                    "Search"
                ],
                "summary": "Search TV Shows",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search Query",
                        "name": "query",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/v1.V1SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/view.MediaRecordCatalog"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/tv/{id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "TV Show"
                ],
                "summary": "Get TV Show Details",
                "parameters": [
                    {
                        "type": "string",
                        "example": "tmdb-1234",
                        "description": "Media ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/v1.V1SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/view.TVShowCatalogObject"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/tv/{id}/episode_groups": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "TV Show"
                ],
                "summary": "Get TV Episode Groups",
                "parameters": [
                    {
                        "type": "string",
                        "example": "tmdb-1234",
                        "description": "Media ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/v1.V1SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/tv/{id}/history": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Watch History"
                ],
                "summary": "Get TV Show Watch History",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Media ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Season number",
                        "name": "seasonNumber",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/v1.V1SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/view.MediaRewatchRecordWatchEvents"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Watch History"
                ],
                "summary": "Add TV Show Watch History",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Media ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Watch History Payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.WatchHistoryTVShowPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/v1.V1SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/v1.AddWatchHistoryTVResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/tv/{id}/history/rewatch": {
            "post": {
                "description": "Create new rewatch for tv show. This archives the previous watches, so user's can start fresh.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Watch History"
                ],
                "summary": "Create TV Show Rewatch",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Media ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/v1.V1SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/database.RewatchRecord"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/tv/{id}/playback": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Watch Progress"
                ],
                "summary": "Set Playback Progress",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Media ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Watch Progress Payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.WatchProgress"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/v1.V1SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/tv/{id}/playback/delete": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Watch Progress"
                ],
                "summary": "Delete Playback Progress",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Media ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Delete Payload (only for TV)",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/v1.DeletePlaybackProgressPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/v1.V1SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/tv/{id}/season/{seasonNumber}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "TV Show"
                ],
                "summary": "Get TV Season Details",
                "parameters": [
                    {
                        "type": "string",
                        "example": "tmdb-1234",
                        "description": "Media ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Season Number",
                        "name": "seasonNumber",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/v1.V1SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/view.TVSeasonCatalogObject"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/tv/{id}/season/{seasonNumber}/history": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Watch History"
                ],
                "summary": "Get TV Show Watch History",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Media ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Season number",
                        "name": "seasonNumber",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/v1.V1SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/view.MediaRewatchRecordWatchEvents"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/tv/{id}/season/{seasonNumber}/playback": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Watch Progress"
                ],
                "summary": "Get Playback Progress",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Media ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Season Number",
                        "name": "seasonNumber",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/v1.V1SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/watch_activity": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Watch History"
                ],
                "summary": "Get Watch Activity for User",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Limit - Defaults at 500",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "2026-03-13T10:20:30Z",
                        "description": "Start time in RFC3339 format",
                        "name": "start_time",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "2026-03-13T10:20:30Z",
                        "description": "End time in RFC3339 format",
                        "name": "end_time",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/v1.V1SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/view.WatchActivityResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.V1ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "database.GenreObject": {
            "type": "object",
            "properties": {
                "genre": {
                    "type": "string"
                },
                "genre_id": {
                    "type": "integer"
                },
                "media_source": {
                    "type": "string"
                },
                "media_type": {
                    "type": "string"
                },
                "source_id": {
                    "type": "integer"
                }
            }
        },
        "database.RewatchRecord": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "record_id": {
                    "description": "record id for movie/show",
                    "type": "integer"
                },
                "rewatch_finished_at": {
                    "type": "string"
                },
                "rewatch_id": {
                    "type": "integer"
                },
                "rewatch_started_at": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "database.TagObject": {
            "type": "object",
            "properties": {
                "tagID": {
                    "type": "integer",
                    "format": "int64"
                },
                "tagName": {
                    "type": "string"
                }
            }
        },
        "database.WatchActivity": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "duration": {
                    "description": "duration/runtime in minutes",
                    "type": "integer"
                },
                "episode_number": {
                    "type": "integer"
                },
                "media_source": {
                    "description": "tmdb, openlibrary, etc. the main metadata provider",
                    "type": "string"
                },
                "media_title": {
                    "description": "movie, tvshow, season or episode title",
                    "type": "string"
                },
                "overview": {
                    "description": "game of thrones is a show about ...",
                    "type": "string"
                },
                "record_id": {
                    "type": "integer"
                },
                "record_type": {
                    "description": "movie,episode",
                    "type": "string"
                },
                "release_date": {
                    "description": "2012-12-30, for shows/seasons - first_air_date, for episodes - air_date",
                    "type": "string"
                },
                "rewatch_id": {
                    "type": "integer"
                },
                "season_number": {
                    "type": "integer"
                },
                "show_media_title": {
                    "type": "string"
                },
                "show_source_id": {
                    "type": "string"
                },
                "source_id": {
                    "description": "tmdb id, episode/movie tmdb id",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "watch_event_id": {
                    "type": "integer"
                },
                "watch_type": {
                    "description": "watch, scrobble",
                    "type": "string"
                },
                "watched_at": {
                    "type": "string"
                }
            }
        },
        "database.WatchEventMediaRecord": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "duration": {
                    "description": "duration/runtime in minutes",
                    "type": "integer"
                },
                "episode_number": {
                    "type": "integer"
                },
                "media_source": {
                    "description": "tmdb, openlibrary, etc. the main metadata provider",
                    "type": "string"
                },
                "media_title": {
                    "description": "movie, tvshow, season or episode title",
                    "type": "string"
                },
                "overview": {
                    "description": "game of thrones is a show about ...",
                    "type": "string"
                },
                "record_id": {
                    "type": "integer"
                },
                "record_type": {
                    "description": "movie,episode",
                    "type": "string"
                },
                "release_date": {
                    "description": "2012-12-30, for shows/seasons - first_air_date, for episodes - air_date",
                    "type": "string"
                },
                "rewatch_id": {
                    "type": "integer"
                },
                "season_number": {
                    "type": "integer"
                },
                "source_id": {
                    "description": "tmdb id, episode/movie tmdb id",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "watch_event_id": {
                    "type": "integer"
                },
                "watch_type": {
                    "description": "watch, scrobble",
                    "type": "string"
                },
                "watched_at": {
                    "type": "string"
                }
            }
        },
        "model.PlayerSettings": {
            "type": "object",
            "properties": {
                "audio_idx": {
                    "type": "integer"
                },
                "audio_lang": {
                    "type": "string"
                },
                "player": {
                    "description": "mpv, exoplayer, etc.",
                    "type": "string"
                },
                "resize_mode": {
                    "description": "whether the video is zoomed to fill/normal, etc.",
                    "type": "string"
                },
                "subtitle_idx": {
                    "type": "integer"
                },
                "subtitle_lang": {
                    "type": "string"
                }
            }
        },
        "model.WatchHistoryMoviePayload": {
            "type": "object",
            "required": [
                "action_type"
            ],
            "properties": {
                "action_type": {
                    "type": "string",
                    "enum": [
                        "watch",
                        "scrobble"
                    ]
                },
                "watched_at": {
                    "type": "string"
                }
            }
        },
        "model.WatchHistoryTVShowPayload": {
            "type": "object",
            "required": [
                "action_type"
            ],
            "properties": {
                "action_type": {
                    "type": "string",
                    "enum": [
                        "watch",
                        "scrobble"
                    ]
                },
                "episode_ids": {
                    "description": "tmdb unique id for episode",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "episode_number": {
                    "type": "integer"
                },
                "rewatch_id": {
                    "type": "integer"
                },
                "season_number": {
                    "type": "integer"
                },
                "watched_at": {
                    "type": "string"
                }
            }
        },
        "model.WatchProgress": {
            "type": "object",
            "required": [
                "current_progress_seconds",
                "total_duration_seconds"
            ],
            "properties": {
                "client_platform": {
                    "description": "android-tv, etc.",
                    "type": "string"
                },
                "current_progress_seconds": {
                    "description": "how many seconds in the user is",
                    "type": "integer"
                },
                "encoded_data": {
                    "description": "for hound-proxied sources",
                    "type": "string"
                },
                "episode_number": {
                    "description": "only defined for shows",
                    "type": "integer"
                },
                "episode_source_id": {
                    "description": "episode source id",
                    "type": "string"
                },
                "episode_title": {
                    "type": "string"
                },
                "last_watched_at": {
                    "description": "last unix time when the playback progress was set",
                    "type": "integer"
                },
                "media_source": {
                    "description": "\"tmdb\"",
                    "type": "string"
                },
                "media_title": {
                    "description": "movie/show title",
                    "type": "string"
                },
                "media_type": {
                    "description": "\"movie\" or \"tvshow\"",
                    "type": "string"
                },
                "overview": {
                    "type": "string"
                },
                "player_settings": {
                    "description": "player, audio, subtitle selections, etc.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.PlayerSettings"
                        }
                    ]
                },
                "release_date": {
                    "type": "string"
                },
                "season_number": {
                    "description": "only defined for shows",
                    "type": "integer"
                },
                "source_id": {
                    "description": "movie/show source id",
                    "type": "string"
                },
                "source_uri": {
                    "description": "magnet, http link, local path",
                    "type": "string"
                },
                "stream_protocol": {
                    "description": "p2p, http, local, etc.",
                    "type": "string"
                },
                "thumbnail_uri": {
                    "type": "string"
                },
                "total_duration_seconds": {
                    "description": "total duration of the media in seconds",
                    "type": "integer"
                }
            }
        },
        "v1.AddToCollectionRequest": {
            "type": "object",
            "required": [
                "media_source",
                "media_type",
                "source_id"
            ],
            "properties": {
                "collection_id": {
                    "type": "integer"
                },
                "media_source": {
                    "type": "string"
                },
                "media_type": {
                    "type": "string"
                },
                "source_id": {
                    "type": "string"
                }
            }
        },
        "v1.AddWatchHistoryTVResponse": {
            "type": "object",
            "properties": {
                "inserted_episode_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "media_source": {
                    "type": "string"
                },
                "skipped_episode_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "v1.DeletePlaybackProgressPayload": {
            "type": "object",
            "properties": {
                "episode_number": {
                    "type": "integer"
                },
                "season_number": {
                    "type": "integer"
                }
            }
        },
        "v1.DeleteWatchHistoryPayload": {
            "type": "object",
            "required": [
                "watch_event_ids"
            ],
            "properties": {
                "watch_event_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "v1.V1ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "error message"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "success",
                        "error"
                    ],
                    "example": "error"
                }
            }
        },
        "v1.V1SuccessResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "status": {
                    "type": "string",
                    "enum": [
                        "success",
                        "error"
                    ],
                    "example": "success"
                }
            }
        },
        "view.CollectionObject": {
            "type": "object",
            "properties": {
                "collection_id": {
                    "type": "integer"
                },
                "collection_title": {
                    "description": "my collection, etc.",
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "is_public": {
                    "type": "boolean"
                },
                "owner_username": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/database.TagObject"
                    }
                },
                "thumbnail_uri": {
                    "description": "url for media thumbnails",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "view.CollectionView": {
            "type": "object",
            "properties": {
                "collection": {
                    "$ref": "#/definitions/view.CollectionObject"
                },
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/view.MediaRecordCatalog"
                    }
                },
                "total_records": {
                    "type": "integer"
                }
            }
        },
        "view.Credit": {
            "type": "object",
            "required": [
                "meta_source",
                "source_id"
            ],
            "properties": {
                "character": {
                    "type": "string"
                },
                "credit_id": {
                    "type": "string"
                },
                "job": {
                    "description": "cast, director, etc.",
                    "type": "string"
                },
                "meta_source": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "original_name": {
                    "type": "string"
                },
                "source_id": {
                    "type": "string"
                },
                "thumbnail_uri": {
                    "description": "profile pic of person",
                    "type": "string"
                }
            }
        },
        "view.MediaRecordCatalog": {
            "type": "object",
            "required": [
                "media_source",
                "media_title",
                "media_type",
                "source_id"
            ],
            "properties": {
                "backdrop_uri": {
                    "type": "string"
                },
                "cast": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/view.Credit"
                    }
                },
                "creators": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/view.Credit"
                    }
                },
                "duration": {
                    "description": "duration/runtime in minutes",
                    "type": "integer"
                },
                "episode_count": {
                    "type": "integer"
                },
                "episode_number": {
                    "type": "integer"
                },
                "extra_data": {
                    "type": "object",
                    "additionalProperties": true
                },
                "genres": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/database.GenreObject"
                    }
                },
                "guest_stars": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/view.Credit"
                    }
                },
                "last_air_date": {
                    "description": "for shows, latest episode air date",
                    "type": "string"
                },
                "logo_uri": {
                    "type": "string"
                },
                "media_source": {
                    "description": "tmdb, openlibrary, etc",
                    "type": "string",
                    "example": "tmdb"
                },
                "media_title": {
                    "type": "string"
                },
                "media_type": {
                    "type": "string",
                    "enum": [
                        "movie",
                        "tvshow"
                    ]
                },
                "next_air_date": {
                    "description": "for shows, next scheduled episode air date",
                    "type": "string"
                },
                "origin_country": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "original_language": {
                    "type": "string"
                },
                "original_title": {
                    "type": "string"
                },
                "overview": {
                    "type": "string"
                },
                "popularity": {
                    "type": "number"
                },
                "release_date": {
                    "type": "string"
                },
                "season_count": {
                    "type": "integer"
                },
                "season_number": {
                    "type": "integer"
                },
                "source_id": {
                    "type": "string"
                },
                "status": {
                    "description": "Returning Series, Released, etc.",
                    "type": "string"
                },
                "thumbnail_uri": {
                    "type": "string"
                },
                "vote_average": {
                    "type": "number"
                },
                "vote_count": {
                    "type": "integer"
                }
            }
        },
        "view.MediaRewatchRecordWatchEvents": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "record_id": {
                    "description": "record id for movie/show",
                    "type": "integer"
                },
                "rewatch_finished_at": {
                    "type": "string"
                },
                "rewatch_id": {
                    "type": "integer"
                },
                "rewatch_started_at": {
                    "type": "string"
                },
                "target_season": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                },
                "watch_events": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/database.WatchEventMediaRecord"
                    }
                }
            }
        },
        "view.TVSeasonCatalogObject": {
            "type": "object",
            "required": [
                "media_source",
                "media_title",
                "media_type",
                "source_id"
            ],
            "properties": {
                "backdrop_uri": {
                    "type": "string"
                },
                "cast": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/view.Credit"
                    }
                },
                "creators": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/view.Credit"
                    }
                },
                "duration": {
                    "description": "duration/runtime in minutes",
                    "type": "integer"
                },
                "episode_count": {
                    "type": "integer"
                },
                "episode_number": {
                    "type": "integer"
                },
                "episodes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/view.MediaRecordCatalog"
                    }
                },
                "extra_data": {
                    "type": "object",
                    "additionalProperties": true
                },
                "genres": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/database.GenreObject"
                    }
                },
                "guest_stars": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/view.Credit"
                    }
                },
                "last_air_date": {
                    "description": "for shows, latest episode air date",
                    "type": "string"
                },
                "logo_uri": {
                    "type": "string"
                },
                "media_source": {
                    "description": "tmdb, openlibrary, etc",
                    "type": "string",
                    "example": "tmdb"
                },
                "media_title": {
                    "type": "string"
                },
                "media_type": {
                    "type": "string",
                    "enum": [
                        "movie",
                        "tvshow"
                    ]
                },
                "next_air_date": {
                    "description": "for shows, next scheduled episode air date",
                    "type": "string"
                },
                "origin_country": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "original_language": {
                    "type": "string"
                },
                "original_title": {
                    "type": "string"
                },
                "overview": {
                    "type": "string"
                },
                "popularity": {
                    "type": "number"
                },
                "release_date": {
                    "type": "string"
                },
                "season_count": {
                    "type": "integer"
                },
                "season_number": {
                    "type": "integer"
                },
                "source_id": {
                    "type": "string"
                },
                "status": {
                    "description": "Returning Series, Released, etc.",
                    "type": "string"
                },
                "thumbnail_uri": {
                    "type": "string"
                },
                "vote_average": {
                    "type": "number"
                },
                "vote_count": {
                    "type": "integer"
                }
            }
        },
        "view.TVShowCatalogObject": {
            "type": "object",
            "required": [
                "media_source",
                "media_title",
                "media_type",
                "source_id"
            ],
            "properties": {
                "backdrop_uri": {
                    "type": "string"
                },
                "cast": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/view.Credit"
                    }
                },
                "creators": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/view.Credit"
                    }
                },
                "duration": {
                    "description": "duration/runtime in minutes",
                    "type": "integer"
                },
                "episode_count": {
                    "type": "integer"
                },
                "episode_number": {
                    "type": "integer"
                },
                "extra_data": {
                    "type": "object",
                    "additionalProperties": true
                },
                "genres": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/database.GenreObject"
                    }
                },
                "guest_stars": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/view.Credit"
                    }
                },
                "last_air_date": {
                    "description": "for shows, latest episode air date",
                    "type": "string"
                },
                "logo_uri": {
                    "type": "string"
                },
                "media_source": {
                    "description": "tmdb, openlibrary, etc",
                    "type": "string",
                    "example": "tmdb"
                },
                "media_title": {
                    "type": "string"
                },
                "media_type": {
                    "type": "string",
                    "enum": [
                        "movie",
                        "tvshow"
                    ]
                },
                "next_air_date": {
                    "description": "for shows, next scheduled episode air date",
                    "type": "string"
                },
                "origin_country": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "original_language": {
                    "type": "string"
                },
                "original_title": {
                    "type": "string"
                },
                "overview": {
                    "type": "string"
                },
                "popularity": {
                    "type": "number"
                },
                "release_date": {
                    "type": "string"
                },
                "season_count": {
                    "type": "integer"
                },
                "season_number": {
                    "type": "integer"
                },
                "seasons": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/view.MediaRecordCatalog"
                    }
                },
                "source_id": {
                    "type": "string"
                },
                "status": {
                    "description": "Returning Series, Released, etc.",
                    "type": "string"
                },
                "thumbnail_uri": {
                    "type": "string"
                },
                "vote_average": {
                    "type": "number"
                },
                "vote_count": {
                    "type": "integer"
                }
            }
        },
        "view.WatchActivityResponse": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "total_records": {
                    "type": "integer"
                },
                "watch_activity": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/database.WatchActivity"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "beta-0.1.0",
	Host:             "localhost:2323",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Hound API Documentation",
	Description:      "Hound Media Server Documentation",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
